disable ci for now

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,278 +1,278 @@
-name: CI
+# name: CI
 
-on:
-  push:
-    branches: [main]
-  pull_request:
-    branches: [main]
+# on:
+#   push:
+#     branches: [main]
+#   pull_request:
+#     branches: [main]
 
-jobs:
-  ci:
-    runs-on: ubuntu-latest
-    container: python:3.11.9-slim
+# jobs:
+#   ci:
+#     runs-on: ubuntu-latest
+#     container: python:3.11.9-slim
 
-    services:
-      mysql:
-        image: mysql:latest
-        ports:
-          - 3306:3306
-        env:
-          MYSQL_DATABASE: django_db
-          MYSQL_PASSWORD: root
-          MYSQL_ROOT_PASSWORD: root
-        options: >-
-          --health-cmd "mysqladmin ping -h localhost -u root --password=$MYSQL_ROOT_PASSWORD"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
+#     services:
+#       mysql:
+#         image: mysql:latest
+#         ports:
+#           - 3306:3306
+#         env:
+#           MYSQL_DATABASE: django_db
+#           MYSQL_PASSWORD: root
+#           MYSQL_ROOT_PASSWORD: root
+#         options: >-
+#           --health-cmd "mysqladmin ping -h localhost -u root --password=$MYSQL_ROOT_PASSWORD"
+#           --health-interval 10s
+#           --health-timeout 5s
+#           --health-retries 5
 
-      minio:
-        image: lazybit/minio
-        ports:
-          - 9000:9000
-        env:
-          MINIO_ROOT_USER: minio
-          MINIO_ROOT_PASSWORD: minio123
-        options: >-
-          --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
+#       minio:
+#         image: lazybit/minio
+#         ports:
+#           - 9000:9000
+#         env:
+#           MINIO_ROOT_USER: minio
+#           MINIO_ROOT_PASSWORD: minio123
+#         options: >-
+#           --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
+#           --health-interval 10s
+#           --health-timeout 5s
+#           --health-retries 5
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v4
 
-      - name: Cache pip dependencies
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
-            ${{ runner.os }}-
-            pip-
+#       - name: Cache pip dependencies
+#         uses: actions/cache@v4
+#         with:
+#           path: ~/.cache/pip
+#           key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
+#           restore-keys: |
+#             ${{ runner.os }}-pip-
+#             ${{ runner.os }}-
+#             pip-
 
-      - name: Set up Docker `
-        uses: docker/setup-buildx-action@v2
+#       - name: Set up Docker `
+#         uses: docker/setup-buildx-action@v2
 
-      - name: Install system dependencies
-        run: |
-          apt-get update && apt-get install -y default-libmysqlclient-dev build-essential pkg-config docker.io curl
+#       - name: Install system dependencies
+#         run: |
+#           apt-get update && apt-get install -y default-libmysqlclient-dev build-essential pkg-config docker.io curl
 
-      - name: Install dependencies and run tests
-        run: |
-          pip install --upgrade pip
-          pip install -r backend/requirements.txt
+#       - name: Install dependencies and run tests
+#         run: |
+#           pip install --upgrade pip
+#           pip install -r backend/requirements.txt
 
-      - name: Test Django application
-        run: |
-          cd backend
-          python manage.py test
-        env:
-          DJANGO_ALLOWED_HOSTS: localhost
-          DATABASE_URL: mysql://root:root@mysql:3306/django_db
-          MINIO_STORAGE_URL: http://minio:9000/blog
-          MINIO_STORAGE_ACCESS_KEY: minio
-          MINIO_STORAGE_SECRET_KEY: minio123
+#       - name: Test Django application
+#         run: |
+#           cd backend
+#           python manage.py test
+#         env:
+#           DJANGO_ALLOWED_HOSTS: localhost
+#           DATABASE_URL: mysql://root:root@mysql:3306/django_db
+#           MINIO_STORAGE_URL: http://minio:9000/blog
+#           MINIO_STORAGE_ACCESS_KEY: minio
+#           MINIO_STORAGE_SECRET_KEY: minio123
 
-      - name: Build Docker image for Django
-        run: |
-          cd backend
-          docker build -t my-django-app:latest .
-        env:
-          DJANGO_ALLOWED_HOSTS: localhost
-          DATABASE_URL: mysql://root:root@mysql:3306/django_db
-          MINIO_STORAGE_URL: http://minio:9000/blog
-          MINIO_STORAGE_ACCESS_KEY: minio
-          MINIO_STORAGE_SECRET_KEY: minio123
+#       - name: Build Docker image for Django
+#         run: |
+#           cd backend
+#           docker build -t my-django-app:latest .
+#         env:
+#           DJANGO_ALLOWED_HOSTS: localhost
+#           DATABASE_URL: mysql://root:root@mysql:3306/django_db
+#           MINIO_STORAGE_URL: http://minio:9000/blog
+#           MINIO_STORAGE_ACCESS_KEY: minio
+#           MINIO_STORAGE_SECRET_KEY: minio123
 
-      - name: Run Django Docker container
-        run: |
-          docker run -d --name django-app --network ${{ job.container.network }} \
-            -p 8000:8000 \
-            -e DATABASE_URL=mysql://root:root@mysql:3306/django_db \
-            -e MINIO_STORAGE_URL=http://minio:9000/blog \
-            -e MINIO_STORAGE_ACCESS_KEY=minio \
-            -e MINIO_STORAGE_SECRET_KEY=minio123 \
-            -e DJANGO_ALLOWED_HOSTS="localhost 127.0.0.1 django-app" \
-            my-django-app:latest
+#       - name: Run Django Docker container
+#         run: |
+#           docker run -d --name django-app --network ${{ job.container.network }} \
+#             -p 8000:8000 \
+#             -e DATABASE_URL=mysql://root:root@mysql:3306/django_db \
+#             -e MINIO_STORAGE_URL=http://minio:9000/blog \
+#             -e MINIO_STORAGE_ACCESS_KEY=minio \
+#             -e MINIO_STORAGE_SECRET_KEY=minio123 \
+#             -e DJANGO_ALLOWED_HOSTS="localhost 127.0.0.1 django-app" \
+#             my-django-app:latest
 
-      - name: Install Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: "20"
+#       - name: Install Node.js
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: "20"
 
-      - name: Cache npm dependencies
-        uses: actions/cache@v4
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-npm-
+#       - name: Cache npm dependencies
+#         uses: actions/cache@v4
+#         with:
+#           path: ~/.npm
+#           key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
+#           restore-keys: |
+#             ${{ runner.os }}-npm-
 
-      - name: Install dependencies
-        working-directory: ./frontend
-        run: |
-          npm install
+#       - name: Install dependencies
+#         working-directory: ./frontend
+#         run: |
+#           npm install
 
-      - name: Build Next.js application
-        working-directory: ./frontend
-        run: |
-          npm run build
-        env:
-          NEXT_PUBLIC_BACKEND_ADDR: http://django-app:8000/
-          NEXT_PUBLIC_STORAGE_ADDR: minio:9000
-          BACKEND_ADDR: http://django-app:8000
-          STORAGE_ADDR: minio:9000
+#       - name: Build Next.js application
+#         working-directory: ./frontend
+#         run: |
+#           npm run build
+#         env:
+#           NEXT_PUBLIC_BACKEND_ADDR: http://django-app:8000/
+#           NEXT_PUBLIC_STORAGE_ADDR: minio:9000
+#           BACKEND_ADDR: http://django-app:8000
+#           STORAGE_ADDR: minio:9000
 
-      - name: Build Docker image for Next.js
-        run: |
-          cd frontend
-          docker build -t my-nextjs-app:latest .
-        env:
-          BACKEND_ADDR: http://django-app:8000/
-          STORAGE_ADDR: minio:9000
+#       - name: Build Docker image for Next.js
+#         run: |
+#           cd frontend
+#           docker build -t my-nextjs-app:latest .
+#         env:
+#           BACKEND_ADDR: http://django-app:8000/
+#           STORAGE_ADDR: minio:9000
 
-      - name: Run Next.js Docker container
-        run: |
-          docker run -d --name nextjs-app -p 3000:3000 \
-            -e BACKEND_ADDR=http://django-app:8000/ \
-            -e NEXT_PUBLIC_BACKEND_ADDR=http://django-app:8000/ \
-            -e STORAGE_ADDR=minio:9000 \
-            -e NEXT_PUBLIC_STORAGE_ADDR="minio:9000" \
-            my-nextjs-app:latest
+#       - name: Run Next.js Docker container
+#         run: |
+#           docker run -d --name nextjs-app -p 3000:3000 \
+#             -e BACKEND_ADDR=http://django-app:8000/ \
+#             -e NEXT_PUBLIC_BACKEND_ADDR=http://django-app:8000/ \
+#             -e STORAGE_ADDR=minio:9000 \
+#             -e NEXT_PUBLIC_STORAGE_ADDR="minio:9000" \
+#             my-nextjs-app:latest
 
-      - name: List Docker images
-        run: docker images
+#       - name: List Docker images
+#         run: docker images
 
-      - name: Save Django Docker image
-        run: |
-          docker save my-django-app:latest -o my-django-app.tar  # Save the image without compression
-          ls -lh my-django-app.tar  # Check the size of the image to ensure it was saved properly
-          gzip my-django-app.tar  # Compress the image after confirming it's saved
-          ls -lh my-django-app.tar.gz  # Check the compressed size
+#       - name: Save Django Docker image
+#         run: |
+#           docker save my-django-app:latest -o my-django-app.tar  # Save the image without compression
+#           ls -lh my-django-app.tar  # Check the size of the image to ensure it was saved properly
+#           gzip my-django-app.tar  # Compress the image after confirming it's saved
+#           ls -lh my-django-app.tar.gz  # Check the compressed size
 
-      - name: Save Next.js Docker image
-        run: |
-          docker save my-nextjs-app:latest -o my-nextjs-app.tar  # Save the image without compression
-          ls -lh my-nextjs-app.tar  # Check the size of the image to ensure it was saved properly
-          gzip my-nextjs-app.tar  # Compress the image after confirming it's saved
-          ls -lh my-nextjs-app.tar.gz  # Check the compressed size
+#       - name: Save Next.js Docker image
+#         run: |
+#           docker save my-nextjs-app:latest -o my-nextjs-app.tar  # Save the image without compression
+#           ls -lh my-nextjs-app.tar  # Check the size of the image to ensure it was saved properly
+#           gzip my-nextjs-app.tar  # Compress the image after confirming it's saved
+#           ls -lh my-nextjs-app.tar.gz  # Check the compressed size
 
-      - name: Upload Django Docker image
-        uses: actions/upload-artifact@v4
-        with:
-          name: my-django-app
-          path: my-django-app.tar.gz
+#       - name: Upload Django Docker image
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: my-django-app
+#           path: my-django-app.tar.gz
 
-      - name: Upload Next.js Docker image
-        uses: actions/upload-artifact@v4
-        with:
-          name: my-nextjs-app
-          path: my-nextjs-app.tar.gz
+#       - name: Upload Next.js Docker image
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: my-nextjs-app
+#           path: my-nextjs-app.tar.gz
 
-  release:
-    needs: [ci]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download django artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: my-django-app
-          path: my-django-app.tar.gz
+#   release:
+#     needs: [ci]
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Download django artifacts
+#         uses: actions/download-artifact@v4
+#         with:
+#           name: my-django-app
+#           path: my-django-app.tar.gz
 
-      - name: Download nextjs artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: my-nextjs-app
-          path: my-nextjs-app.tar.gz
+#       - name: Download nextjs artifacts
+#         uses: actions/download-artifact@v4
+#         with:
+#           name: my-nextjs-app
+#           path: my-nextjs-app.tar.gz
 
-      - name: Get short SHA
-        id: slug
-        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
+#       - name: Get short SHA
+#         id: slug
+#         run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
 
-      - name: Create release
-        uses: softprops/action-gh-release@v1
-        with:
-          files: |
-            my-django-app.tar.gz
-            my-nextjs-app.tar.gz
-          tag_name: ${{ steps.slug.outputs.sha7 }} # Use the short SHA as the tag name
-          body: |
-            This is an automated release.
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#       - name: Create release
+#         uses: softprops/action-gh-release@v1
+#         with:
+#           files: |
+#             my-django-app.tar.gz
+#             my-nextjs-app.tar.gz
+#           tag_name: ${{ steps.slug.outputs.sha7 }} # Use the short SHA as the tag name
+#           body: |
+#             This is an automated release.
+#         env:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Push release
-        run: echo "Release pushed with tag ${{ steps.slug.outputs.sha7 }}!"
+#       - name: Push release
+#         run: echo "Release pushed with tag ${{ steps.slug.outputs.sha7 }}!"
 
-  cd:
-    needs: [ci]
-    environment: DJANGO_ALLOWED_HOSTS
-    runs-on: ubuntu-latest
-    steps:
-      - name: Cache apt packages
-        uses: actions/cache@v3
-        with:
-          path: /var/cache/apt
-          key: wireguard-${{ runner.os }}-apt-${{ hashFiles('**/setup.sh') }}
-          restore-keys: |
-            wireguard-${{ runner.os }}-apt-
+#   cd:
+#     needs: [ci]
+#     environment: DJANGO_ALLOWED_HOSTS
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Cache apt packages
+#         uses: actions/cache@v3
+#         with:
+#           path: /var/cache/apt
+#           key: wireguard-${{ runner.os }}-apt-${{ hashFiles('**/setup.sh') }}
+#           restore-keys: |
+#             wireguard-${{ runner.os }}-apt-
 
-      - name: Install WireGuard client
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y wireguard
+#       - name: Install WireGuard client
+#         run: |
+#           sudo apt-get update
+#           sudo apt-get install -y wireguard
 
-      - name: Setup WireGuard Configuration
-        run: |
-          umask 077
-          echo "[Interface]
-          PrivateKey = ${{ secrets.WG_CLIENT_PRIVATE_KEY }}
-          Address = 10.253.0.2/32
+#       - name: Setup WireGuard Configuration
+#         run: |
+#           umask 077
+#           echo "[Interface]
+#           PrivateKey = ${{ secrets.WG_CLIENT_PRIVATE_KEY }}
+#           Address = 10.253.0.2/32
 
-          [Peer]
-          PresharedKey = ${{ secrets.WG_PRESHARED_KEY }}
-          PublicKey = ${{ secrets.WG_SERVER_PUBLIC_KEY }}
-          Endpoint = ${{ secrets.WG_SERVER_ENDPOINT }}
-          AllowedIPs = 10.253.0.1/32, 192.168.1.0/24" | sudo tee /etc/wireguard/wg0.conf
+#           [Peer]
+#           PresharedKey = ${{ secrets.WG_PRESHARED_KEY }}
+#           PublicKey = ${{ secrets.WG_SERVER_PUBLIC_KEY }}
+#           Endpoint = ${{ secrets.WG_SERVER_ENDPOINT }}
+#           AllowedIPs = 10.253.0.1/32, 192.168.1.0/24" | sudo tee /etc/wireguard/wg0.conf
 
-      - name: Start WireGuard Client
-        run: |
-          sudo wg-quick up wg0
-          sleep 5
+#       - name: Start WireGuard Client
+#         run: |
+#           sudo wg-quick up wg0
+#           sleep 5
 
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: my-django-app
-          path: .
+#       - name: Download artifacts
+#         uses: actions/download-artifact@v4
+#         with:
+#           name: my-django-app
+#           path: .
 
-      - name: Download Next.js artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: my-nextjs-app
-          path: .
+#       - name: Download Next.js artifacts
+#         uses: actions/download-artifact@v4
+#         with:
+#           name: my-nextjs-app
+#           path: .
 
-      - name: copy file via ssh password
-        uses: appleboy/scp-action@v0.1.7
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: ${{ secrets.SERVER_PORT }}
-          source: "my-django-app.tar.gz,my-nextjs-app.tar.gz"
-          target: ${{ secrets.SERVER_PATH }}
+#       - name: copy file via ssh password
+#         uses: appleboy/scp-action@v0.1.7
+#         with:
+#           host: ${{ secrets.SERVER_HOST }}
+#           username: ${{ secrets.SERVER_USERNAME }}
+#           key: ${{ secrets.SSH_PRIVATE_KEY }}
+#           port: ${{ secrets.SERVER_PORT }}
+#           source: "my-django-app.tar.gz,my-nextjs-app.tar.gz"
+#           target: ${{ secrets.SERVER_PATH }}
 
-      - name: SSH into server using SSH key
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: ${{ secrets.SERVER_PORT }}
-          script: |
-            cd ${{ secrets.SERVER_PATH }}
-            echo "Commit hash: $(git rev-parse HEAD)" >> commit.txt
-            bash deploy.sh
+#       - name: SSH into server using SSH key
+#         uses: appleboy/ssh-action@master
+#         with:
+#           host: ${{ secrets.SERVER_HOST }}
+#           username: ${{ secrets.SERVER_USERNAME }}
+#           key: ${{ secrets.SSH_PRIVATE_KEY }}
+#           port: ${{ secrets.SERVER_PORT }}
+#           script: |
+#             cd ${{ secrets.SERVER_PATH }}
+#             echo "Commit hash: $(git rev-parse HEAD)" >> commit.txt
+#             bash deploy.sh
